---
name: Lint code review

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: { }

jobs:
  lint_docker_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Docker lint check
#        uses: uditgaurav/docker-linter@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          DOCKERFILE: Dockerfile
        run: echo "dockerfile lint successful"
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download schema
        run: wget https://apps.nextcloud.com/schema/apps/info.xsd
      - name: Enable annotations for validation errors and warnings
        uses: korelstar/xmllint-problem-matcher@v1
#      - name: Validate info.xml using XML schema info.xsd
#        uses: ChristophWurst/xmllint-action@v1
#        with:
#          xml-file: ./appinfo/info.xml
#          xml-schema-file: ./info.xsd