---
name: Lint code review

on:  # yamllint disable-line rule:truthy
  push: null
  pull_request: null

permissions: { }

jobs:
  lint_docker_file:
    runs-on: ubuntu-latest
    steps:
      - name: lint docker file
        uses: rusty-actions/dockerfile-linter@v1
        with:
          dockerfile: Dockerfile
#  xmllint:
#    stage: linting
#    image: registry.gitlab.com/pipeline-components/xmllint:latest
#    script:
#      - find . -iname "*.xml" -type f -exec xmllint --noout {} \+

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Yaml Lint
        uses: kapost/yaml-linter@v1
#        env:
#          CUSTOM_CONFIG: custom-yaml.yml 
#          TARGET_DIRECTORY: ./my-directory 

      - name: Checkout
        uses: actions/checkout@v4
      - name: Download schema
        run: wget https://apps.nextcloud.com/schema/apps/info.xsd
      - name: Enable annotations for validation errors and warnings
        uses: korelstar/xmllint-problem-matcher@v1
      - name: Validate info.xml using XML schema info.xsd
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./appinfo/info.xml
          xml-schema-file: ./info.xsd